name: warp
version: stable
version-script: git -C parts/warp/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  Warp tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  warp:
    command: bin/warp
    environment:
        PYTHONIOENCODING: utf-8

parts:
  warp:
    source: https://github.com/MaxGrosshandler/warp.git
    plugin: python
